### ISSUE TITLE
Develop *.Rd files for exported functions

### ISSUE THREAD

**Issue by esuxiao** [esuxiao/mmeta#15]
# Background
The name and syntax of exported functions have changed. Then new Rd files need to be developed. 

# Task
- [x] #16

-  [Single Table](https://docs.google.com/document/d/18Uque2u0FP_Od4I3f7aBlfQ9-nvZEdzy/edit?usp=share_link&ouid=116560654731964599691&rtpof=true&sd=true)

- [Multiple Table](https://docs.google.com/document/d/19ywXMfYUZ4zCBrVbZo3HHJPpEXa6eq5k/edit?usp=share_link&ouid=116560654731964599691&rtpof=true&sd=true)

Develop the Rd files for the following functions:
- [x]  SingleTable.create
- [x]  SingleTable.modelFit
- [x]  SingleTable.summary  
- [x]  SingleTable.plot, 
- [x] MultipleTables.create, 
- [x] MultipleTables.modelFit,
- [x] MultipleTables.summary
- [x] MultipleTables.plot

# Reference
examples to show how to use the user interface:

**Comment by esuxiao** [comment]
@jchen1992 Hi Jiajie, you can start to develop Rd files and commit them to branch `V3.0_dev`. I set the deadline as 1/6/2023. Does this deadline works for you? 

When you start to work on this task, please move this card to `In progress` column and keep update the status by clicking the bottoms of to-do lists.

After your finish this task, please move this card to `In review` column.

**Comment by jchen1992** [comment]
I will try my best to meet the deadline, though this is my first time to develop a R package.
I am not familiar with GitHub Projects, but it seems nothing is under the 'Projects'? Could you create an item in the Projects board so that I can change the status to 'in progress'?

**Comment by jchen1992** [comment]
@esuxiao Hi Xiao, the new examples are written in the [Single Table](https://docs.google.com/document/d/18Uque2u0FP_Od4I3f7aBlfQ9-nvZEdzy/edit?usp=share_link&ouid=116560654731964599691&rtpof=true&sd=true) and [Multiple Table](https://docs.google.com/document/d/19ywXMfYUZ4zCBrVbZo3HHJPpEXa6eq5k/edit?usp=share_link&ouid=116560654731964599691&rtpof=true&sd=true),right?

**Comment by esuxiao** [comment]
> @esuxiao Hi Xiao, the new examples are written in the [Single Table](https://docs.google.com/document/d/18Uque2u0FP_Od4I3f7aBlfQ9-nvZEdzy/edit?usp=share_link&ouid=116560654731964599691&rtpof=true&sd=true) and [Multiple Table](https://docs.google.com/document/d/19ywXMfYUZ4zCBrVbZo3HHJPpEXa6eq5k/edit?usp=share_link&ouid=116560654731964599691&rtpof=true&sd=true),right?

@jchen1992 Yes. Please remember to use ` \donttest{}` because those examples take more than 5 seconds.

**Comment by esuxiao** [comment]
> I will try my best to meet the deadline, though this is my first time to develop a R package. I am not familiar with GitHub Projects, but it seems nothing is under the 'Projects'? Could you create an item in the Projects board so that I can change the status to 'in progress'?

@jchen1992 Can you access to the project via the following link?
https://github.com/users/esuxiao/projects/6

**Comment by jchen1992** [comment]
> > I will try my best to meet the deadline, though this is my first time to develop a R package. I am not familiar with GitHub Projects, but it seems nothing is under the 'Projects'? Could you create an item in the Projects board so that I can change the status to 'in progress'?
> 
> @jchen1992 Can you access to the project via the following link? https://github.com/users/esuxiao/projects/6

No, this link shows 'page not found'. Maybe I don't have access?

**Comment by esuxiao** [comment]
@jchen1992 I have change the project status as `public`. Can you access to it now? https://github.com/users/esuxiao/projects/6

**Comment by jchen1992** [comment]
I have a question about a1,b1,a2,b2,rho. I thought the parameters (a1,b1,a2,b2,rho) are computed by optimizing the loglikehood,  and the only input was 

> @jchen1992 I have change the project status as `public`. Can you access to it now? https://github.com/users/esuxiao/projects/6

Yes, I can access the board now.

**Comment by jchen1992** [comment]
> @jchen1992 I have change the project status as `public`. Can you access to it now? https://github.com/users/esuxiao/projects/6

Yes, Thanks!

**Comment by jchen1992** [comment]
I have a question about the input parameters. I thought the singletable parameters (a1,b1,a2,b2,rho) are computed by optimizing the Loglikehood and only inputs are (y1,n1,y2,n2,...)? Does (a1,b1,a2,b2,rho) mean initial values for the optimization?

**Comment by esuxiao** [comment]
> I have a question about the input parameters. I thought the singletable parameters (a1,b1,a2,b2,rho) are computed by optimizing the Loglikehood and only inputs are (y1,n1,y2,n2,...)? Does (a1,b1,a2,b2,rho) mean initial values for the optimization?

@jchen1992 would you please repose this question in `Discussion` ?
