### ISSUE TITLE
[HELP NEED] Bug fixing for v3.0 dev. 1 error 2 notes

### ISSUE THREAD

**Issue by jchen1992** [esuxiao/mmeta#23]
@esuxiao I summarized the check report for current version. There are some tricky issues:

1. Non staged note 
https://github.com/esuxiao/mmeta/blob/7d4b47d0bdb5d0f5f73b90a43d21722048aeb02e/00check.log#L18-L21
This note is related to the description file: https://github.com/esuxiao/mmeta/blob/bff00737f4516fd67d8d21ecc5c8111a1742fecc/DESCRIPTION#L30 

2. forestPlot: no visible binding for global variable?
https://github.com/esuxiao/mmeta/blob/7d4b47d0bdb5d0f5f73b90a43d21722048aeb02e/00check.log#L43-L51
This is another note related to codes in the _MultipleTables-method-internal.R_

3. Error in 1:num_studies : argument of length 0
Calls: MultipleTables.plot -> MultipleTables._plotForest
https://github.com/esuxiao/mmeta/blob/7d4b47d0bdb5d0f5f73b90a43d21722048aeb02e/00check.log#L69-L123
This error is in the **examples** for _multipleTables.plot_ 
https://github.com/esuxiao/mmeta/blob/bff00737f4516fd67d8d21ecc5c8111a1742fecc/R/MultipleTables-method-exported.R#L386-L387
Call for forest plot halted. Probably this error is caused by the above note?

Thanks in advance!

**Comment by esuxiao** [comment]
@jchen1992 Hi Jiajie, please repose the check log and error in `GitHub Discussion` since I have already deleted the folder.

**Comment by esuxiao** [comment]
# Check log and error messge
> * using log directory 'C:/Users/thech/Documents/R files/mmeta3/mmeta.Rcheck'
* using R version 4.2.2 (2022-10-31 ucrt)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: UTF-8
* using options '--no-manual --as-cran'
* checking for file 'mmeta/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'mmeta' version '3.0'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking serialization versions ... OK
* checking whether package 'mmeta' can be installed ... NOTE
Found the following notes/warnings:
  Non-staged installation was used
See 'C:/Users/thech/Documents/R files/mmeta3/mmeta.Rcheck/00install.out' for details.
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... [11s] NOTE
forestPlot: no visible binding for global variable 'study_id'
forestPlot: no visible binding for global variable 'ET_lower'
forestPlot: no visible binding for global variable 'ET_upper'
samplePosteriorIndependent: no visible global function definition for
  'parmsPosteriorIndependentCal'
samplePosteriorIndependent: no visible binding for global variable
  'parms_prior'
Undefined global functions or variables:
  ET_lower ET_upper parmsPosteriorIndependentCal parms_prior study_id
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... OK
* checking compiled code ... OK
* checking examples ... OK
* checking examples with --run-donttest ... [242s] ERROR
Running examples in 'mmeta-Ex.R' failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: MultipleTables.plot
> ### Title: Plot Method for 'Multipletables' objects
> ### Aliases: MultipleTables.plot
> 
> ### ** Examples
> 
> ## No test: 
>  library(mmeta)
>  library(ggplot2)
>  ## Analyze the dataset colorectal to conduct exact inference of the odds ratios
>  data(colorectal)
>  colorectal['study_name'] <- colorectal['studynames']
>  ## If exact method is used, the codes for sampling method are similar.
>  ## Create object multiple_tables_obj_exact
>  multiple_tables_obj_exact <- MultipleTables.create(data=colorectal,
+   measure='OR', model= 'Sarmanov')
>  ## Model fit default
>  multiple_tables_obj_exact <- MultipleTables.modelFit(multiple_tables_obj_exact, method = 'exact')
>  ## Density plot, overlay
>  ## Note: There are no enough types of line, if we have too many densities!
>  MultipleTables.plot(multiple_tables_obj_exact, plot_type = 'density',
+  layout_type = 'overlay')
>  ## Choose Set by = ‘color’
>  MultipleTables.plot(multiple_tables_obj_exact, plot_type = 'density',
+  layout_type = 'overlay',by = 'color')
>  ## Set by = ‘color’ and specify xlim as 0 to 5.
>  MultipleTables.plot(multiple_tables_obj_exact, plot_type = 'density',
+  layout_type = 'overlay', by = 'color', xlim = c(0,5))
Warning: Removed 37334 rows containing missing values (`geom_line()`).
>  ## Set by = ‘color’ and specify xlim as 0 to 5 and add vertical line at OR = 1
>  MultipleTables.plot(multiple_tables_obj_exact, plot_type = 'density',
+  layout_type = 'overlay', by = 'color',xlim = c(0,5), add_vertical = 1)
Warning: Removed 37334 rows containing missing values (`geom_line()`).
>  ## If select three studies
>  MultipleTables.plot(multiple_tables_obj_exact, plot_type = 'density',
+  layout_type = 'overlay',selected_study_names = c('Bell','Chen','Oda'), xlim = c(0,5))
Warning: Removed 5682 rows containing missing values (`geom_line()`).
>  ## We can add external layouts for the return ggplot2 : * xlab as Odds ratio
>  ggplot2_obj <- MultipleTables.plot(multiple_tables_obj_exact,
+  plot_type = 'density', layout_type = 'overlay', by = 'color',xlim = c(0,5))
>  ggplot2_obj + xlab('Odds Ratio')  + ggtitle('OR ration for XX cancer')
Warning: Removed 37334 rows containing missing values (`geom_line()`).
>  ## density plot, plot side by side
>  MultipleTables.plot(multiple_tables_obj_exact, plot_type = 'density',
+  layout_type = 'side_by_side')
>  ## Forest plot (default)
>  MultipleTables.plot(multiple_tables_obj_exact, plot_type = 'forest')
Error in 1:num_studies : argument of length 0
Calls: MultipleTables.plot -> MultipleTables._plotForest
Execution halted
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE
Status: 1 ERROR, 2 NOTEs

**Comment by esuxiao** [comment]
Hi @jchen1992  : `no visible binding for global variable` indicates  the R program can not find some variables by name in the given environment, such as  `parmsPosteriorIndependentCal` , `ET_lower` , `ET_upper` .  The problems associated with   `ET_lower` , `ET_upper`  are related to name space.  The problem associated  with `parmsPosteriorIndependentCal` is easy to identify if you read the related functions.  I suggests you try to find some hints by yourself.

**Comment by jchen1992** [comment]
> Hi @jchen1992 : `no visible binding for global variable` indicates the R program can not find some variables by name in the given environment, such as `parmsPosteriorIndependentCal` , `ET_lower` , `ET_upper` . The problems associated with `ET_lower` , `ET_upper` are related to name space. The problem associated with `parmsPosteriorIndependentCal` is easy to identify if you read the related functions. I suggests you try to find some hints by yourself.

OK, I will look into it.

**Comment by jchen1992** [comment]
@esuxiao 

_Error in 1:num_studies : argument of length 0
Calls: MultipleTables.plot -> MultipleTables._plotForest
Execution halted_
This error has been fixed by adding:
https://github.com/esuxiao/mmeta/blob/182318757b2af9b78f58feae865e9bd5cfb94f88/man/MultipleTables.plot.Rd#L73-L74.

**Comment by jchen1992** [comment]
### New check log

── R CMD check ────────────────────────
─  using log directory 'C:/Users/thech/Documents/R files/mmeta3/mmeta.Rcheck' (368ms)
─  using R version 4.2.2 (2022-10-31 ucrt)
─  using platform: x86_64-w64-mingw32 (64-bit)
─  using session charset: UTF-8
─  using options '--no-manual --as-cran'
✔  checking for file 'mmeta/DESCRIPTION'
─  checking extension type ... Package
─  this is package 'mmeta' version '3.0'
─  package encoding: UTF-8
✔  checking package namespace information
✔  checking package dependencies (3.2s)
✔  checking if this is a source package ...
✔  checking if there is a namespace
✔  checking for executable files (789ms)
✔  checking for hidden files and directories ...
✔  checking for portable file names
✔  checking serialization versions
N  checking whether package 'mmeta' can be installed (6.8s)
   Found the following notes/warnings:
     Non-staged installation was used
   See 'C:/Users/thech/Documents/R files/mmeta3/mmeta.Rcheck/00install.out' for details.
✔  checking installed package size ... 
✔  checking package directory (350ms)
✔  checking for future file timestamps ... 
✔  checking DESCRIPTION meta-information (367ms)
✔  checking top-level files ...
✔  checking for left-over files
✔  checking index information
✔  checking package subdirectories ... 
✔  checking R files for non-ASCII characters ... 
✔  checking R files for syntax errors ... 
✔  checking whether the package can be loaded (997ms)
✔  checking whether the package can be loaded with stated dependencies (777ms)
✔  checking whether the package can be unloaded cleanly (883ms)
✔  checking whether the namespace can be loaded with stated dependencies (788ms)
✔  checking whether the namespace can be unloaded cleanly (1.1s)
✔  checking loading without being on the library search path (1.1s)
✔  checking dependencies in R code (999ms)
✔  checking S3 generic/method consistency (1.3s)
✔  checking replacement functions (899ms)
✔  checking foreign function calls (1s)
─  checking R code for possible problems ... [11s] NOTE (10.8s)
   forestPlot: no visible binding for global variable 'study_id'
   forestPlot: no visible binding for global variable 'ET_lower'
   forestPlot: no visible binding for global variable 'ET_upper'
   samplePosteriorIndependent: no visible global function definition for
     'parmsPosteriorIndependentCal'
   samplePosteriorIndependent: no visible binding for global variable
     'parms_prior'
   Undefined global functions or variables:
     ET_lower ET_upper parmsPosteriorIndependentCal parms_prior study_id
✔  checking Rd files (375ms)
✔  checking Rd metadata ... 
✔  checking Rd line widths ... 
✔  checking Rd cross-references ... 
✔  checking for missing documentation entries (898ms)
✔  checking for code/documentation mismatches (2.4s)
✔  checking Rd \usage sections (1.6s)
✔  checking Rd contents ... 
✔  checking for unstated dependencies in examples ... 
✔  checking contents of 'data' directory (1.3s)
✔  checking data for non-ASCII characters ... 
✔  checking data for ASCII and uncompressed saves (349ms)
✔  checking line endings in C/C++/Fortran sources/headers ...
✔  checking pragmas in C/C++ headers and code
✔  checking compilation flags used
✔  checking compiled code (2.2s)
✔  checking examples (1.8s)
─  checking examples with --run-donttest ... [317s] OK (5m 17.1s)
✔  checking for non-standard things in the check directory
✔  checking for detritus in the temp directory
   
   See
     'C:/Users/thech/Documents/R files/mmeta3/mmeta.Rcheck/00check.log'
   for details.
   
   
── R CMD check results ─ mmeta 3.0 ────
Duration: 6m 6.2s

❯ checking whether package 'mmeta' can be installed ... NOTE
  See below...

❯ checking R code for possible problems ... [11s] NOTE
  forestPlot: no visible binding for global variable 'study_id'
  forestPlot: no visible binding for global variable 'ET_lower'
  forestPlot: no visible binding for global variable 'ET_upper'
  samplePosteriorIndependent: no visible global function definition for
    'parmsPosteriorIndependentCal'
  samplePosteriorIndependent: no visible binding for global variable
    'parms_prior'
  Undefined global functions or variables:
    ET_lower ET_upper parmsPosteriorIndependentCal parms_prior study_id

**Comment by jchen1992** [comment]
@esuxiao 
By the way, do we decide to ignore the following note?
N checking whether package 'mmeta' can be installed (6.8s)
Found the following notes/warnings:
Non-staged installation was used

**Comment by esuxiao** [comment]
> @esuxiao By the way, do we decide to ignore the following note? N checking whether package 'mmeta' can be installed (6.8s) Found the following notes/warnings: Non-staged installation was used

You may remove the following line in DESCRIPTION file: 
[StagedInstall: no](https://github.com/esuxiao/mmeta/blob/e61c8601e7e20ce0f481ee37707b6cd4f5fa259d/DESCRIPTION#L30)

But in this case, I cannot install the package from GitHub directly with the `non-zero exit status` error.  Sorry, I cannot provide any help for this issue because I am not very familiar R package development.
