### ISSUE TITLE
Release mmeta V3.0 formal to CRAN

### ISSUE THREAD

**Issue by esuxiao** [esuxiao/mmeta#28]
# Dependent tasks
* Release V3.0(advanced) formal in Github

# Task

- [ ] Release mmeta V3.0(advanced) to CRAN via devtool

**Comment by esuxiao** [comment]
Hi @jchen1992 , please complete the dependent task before you worked on the ticket.

**Comment by jchen1992** [comment]
> Hi @jchen1992 , please complete the dependent task before you worked on the ticket.

Do you want to create a new branch to upload the package? the current codes in branch V3.0_dev are already the alpha version.

**Comment by esuxiao** [comment]
> > Hi @jchen1992 , please complete the dependent task before you worked on the ticket.
> 
> Do you want to create a new branch to upload the package? the current codes in branch V3.0_dev are already the alpha version.

No. I mean merge the branch `V3.0_dev` with main branch and use `release` function of GItHub.

**Comment by jchen1992** [comment]
> > > Hi @jchen1992 , please complete the dependent task before you worked on the ticket.
> > 
> > 
> > Do you want to create a new branch to upload the package? the current codes in branch V3.0_dev are already the alpha version.
> 
> No. I mean merge the branch `V3.0_dev` with main branch and use `release` function of GItHub.

@esuxiao I have merged the V3.0_dev to the main branch. Do you want to delete the V3.0_dev branch?

**Comment by jchen1992** [comment]
The V3.0 is released to CRAN. This issue can be closed.
